import { defineConfig } from 'drizzle-kit'

// Note: the SQLite database is generated by scripts/build-db.py (see `npm run db:build`),
// so Drizzle is used for read-only typing and Studio — no migrations are authored here.
export default defineConfig({
  schema: './drizzle/schema.ts',
  dialect: 'sqlite',
  dbCredentials: {
    url: './data/rej-studio.db',
  },
})
